"""empty message

Revision ID: 2ab835ab5cb6
Revises: 
Create Date: 2022-06-19 20:30:11.338954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab835ab5cb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fleet', sa.Column('number_plate', sa.String(length=80),
                                     nullable=False))
    op.create_unique_constraint(None, 'fleet', ['number_plate'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fleet', type_='unique')
    op.drop_column('fleet', 'number_plate')
    # ### end Alembic commands ###
